abstract class AppString {
  static const String dalel = "Dalel",
      skip = "Skip",
      next = "Next",
      createAccount = "Create Account",
      loginNow = "Login Now",
      exploreThehistorywith = "Explore The history with",
      dalelinasmartway = "Dalel in a smart way",
      usingourappshistorylibraries = "Using our app’s history libraries",
      youcanfindmanyhistoricalperiods = "you can find many historical periods ",
      fromEveryPlace = "From every place",
      onEarth = "on earth",
      aBigVarietyOfAncientPlaces = "A big variety of ancient places",
      fromAllOverTheWorld = "from all over the world",
      usingModernAiTechnology = "Using modern AI technology",
      forBetterUserExperience = "for better user experience",
      aiProvideRecommendationsAndHelps = "AI provide recommendations and helps",
      youToContinueTheSearchJourney = "you to continue the search journey",
      //!auth Strings
      welcome = "Welcome !",
      firstName = "First Name",
      lastName = "Last Name",
      emailAddress = "Email Address",
      password = "Password",
      welcomeBack = "Welcome Back !",
      iHaveAgreeToOurTermsAndCondition =
          "I have agree to our Terms and Condition",
      signUp = "Sign Up",
      signIn = "Sign In",
      alreadyHaveAnAccount = "Already have an account ?",
      dontHaveAnAccount = "Don’t have an account ?",
      forgotPassword = "Forgot Password ?",
      //!Home Strings
      recommendations = "Recommendations",
      aboutAncientEgypt = "About Ancient Egypt",
      ancientEgyptWars = "Ancient Egypt Wars",
      //!Search Strings
      searchDeepIntoTheHistory = "Search deep into the history",
      recent = "Recent",
      //!Profile Strings
      profile = "Profile",
      account = "Account",
      editProfile = "Edit Profile",
      notification = "Notification",
      general = "General",
      settings = "Settings",
      security = "Security",
      privacyPolicy = "Privacy Policy",
      logOut = "Log Out",
      //!Bazar
      bazar = "Bazar",
      historyBooks = "History Books",
      historicalSouvenirs = "Historical Souvenirs",
      //!Cart
      myCart = "My Cart",
      totalPayment = "Total Payment",
      checkoutNow = "Checkout Now",
      //!Payment Strings
      checkoutScreen = "Checkout Screen",
      deliveryAddress = "Delivery Address",
      change = "Change",
      items = "1 items",
      selectedProduct = "Selected Product",
      paymentMethod = "Payment Method",
      confirmPayment = "Confirm Payment",
      orderSuccess = "Order Success",
      thankYou =
          "Thank you for your order here and your package will be sent to your address very quickly and fast good product",
      backToHome = "Back To Home",
      //!Forgot password
      forgotPasswordPage = "Forgot Password",
      sendVerificationCode = "Send Verification Code",
      verificationNow = "Verification Now",
      resendCode = "Resend Code",
      verifyAccount = "Verify Account",
      enter4DigitCodeWeHaveSentTo = "Enter 4 digit code we have sent to ",
      haventReceivedVerificationCode = "Haven’t received verification code?"
      ;
}
