// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs44LGWHESoQTJj7gdP9OIGyRDdigXblQ',
    appId: '1:661747887240:web:0e6a198de09f687a00833d',
    messagingSenderId: '661747887240',
    projectId: 'dalel-app-9ddfa',
    authDomain: 'dalel-app-9ddfa.firebaseapp.com',
    storageBucket: 'dalel-app-9ddfa.firebasestorage.app',
    measurementId: 'G-864DNR4TYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPtxh2F9akVTJUINFyQ8dreOMykZA_stM',
    appId: '1:661747887240:android:6712a453f359efaf00833d',
    messagingSenderId: '661747887240',
    projectId: 'dalel-app-9ddfa',
    storageBucket: 'dalel-app-9ddfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2V3JBerUzYeKQv1p6ld0zi8jQJbYnnLA',
    appId: '1:661747887240:ios:aba20fc6373efdd400833d',
    messagingSenderId: '661747887240',
    projectId: 'dalel-app-9ddfa',
    storageBucket: 'dalel-app-9ddfa.firebasestorage.app',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2V3JBerUzYeKQv1p6ld0zi8jQJbYnnLA',
    appId: '1:661747887240:ios:aba20fc6373efdd400833d',
    messagingSenderId: '661747887240',
    projectId: 'dalel-app-9ddfa',
    storageBucket: 'dalel-app-9ddfa.firebasestorage.app',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs44LGWHESoQTJj7gdP9OIGyRDdigXblQ',
    appId: '1:661747887240:web:7f4198759e903e5900833d',
    messagingSenderId: '661747887240',
    projectId: 'dalel-app-9ddfa',
    authDomain: 'dalel-app-9ddfa.firebaseapp.com',
    storageBucket: 'dalel-app-9ddfa.firebasestorage.app',
    measurementId: 'G-79ERKF0RLK',
  );
}
